### PR TITLE
Bump version to 1.3.5

### PR DESCRIPTION
**Pull request by molinav**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by molinav** [comment]
@conda-forge-admin, please rerender

**Comment by molinav** [comment]
The pipelines are failing due to a checksum failure after downloading the source package, but I have no idea what is causing it.

**Comment by molinav** [comment]
I will wait until the end of the day in case @ReimarBauer or @ocefpaf want to add something and then I will merge it.

**Comment by ocefpaf** [comment]
> I will wait until the end of the day in case @ReimarBauer or @ocefpaf want to add something and then I will merge it.

LGTM! Thanks for carrying the torch for basemap.

**Pull request merged**
