### PR TITLE
rebuild to get geos 3.10 into the package list

### PR DESCRIPTION
**Pull request by ReimarBauer**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
seems not be possible for me to get the requirements for python_abi in py37 added
https://github.com/conda-forge/python_abi-feedstock/pull/15

**Review by molinav — APPROVED** [review]

**Comment by molinav** [comment]
I was a bit surprised to see that the recipe is already depending on GEOS >= 3.9, when it is known to cause bugs in `basemap` (see https://github.com/matplotlib/basemap/issues/522). The recipe will have the same issues with GEOS 3.10 until the problem is solved on the `basemap` side, so accepting GEOS 3.10 is not a regression actually.

**Comment by ReimarBauer** [comment]
Thx for noting this geos problem. We had before a different problem for fixating it <3.9 
I try if I can help with basemap 1.3.3

**Comment by molinav** [comment]
@ReimarBauer That would be of great help, since I am not a real expert on conda-forge packaging. This feedstock stays for the moment in `basemap` 1.2.x because for 1.3.x I made some significant changes in the `basemap` packaging which require an update in the conda-forge recipe (see https://github.com/conda-forge/basemap-feedstock/issues/87).

To make the distribution of PyPI packages easier, I split `basemap` into `basemap`, `basemap-data` and `basemap-data-hires`, because this allows me to generate light wheels with the code for every Python version ([basemap](https://pypi.org/project/basemap/)) and two universal data wheels for all Python versions (mandatory [basemap-data](https://pypi.org/project/basemap-data/) and optional [basemap-data-hires](https://pypi.org/project/basemap-data-hires/)). I took this idea from the conda-forge package, whose recipe was splitting `basemap` into `basemap` and `basemap-data-hires`. The packages `basemap-data-hires` for PyPI and conda-forge are currently not identical (the PyPI package also contains the intermediate resolution data files).

The goal would be to have this new three-package structure also in conda-forge. For this, the conda-forge recipe needs to be updated, so that `basemap-data-hires-feedstock` gets archived and `basemap-feedstock` takes care creating these three new conda-forge packages. The Anaconda contributors have already migrated their recipe, see https://github.com/AnacondaRecipes/basemap-feedstock/commit/d5d5c3c715857069f79098f3ca4939159f2f1074. They tried to merge it here but both feedstocks have diverged too much and the merge was not possible.

I guess the most important part is to mimic what the Anaconda contributors did in their `recipe` folder.

**Pull request merged**
